### ISSUE TITLE
在线急等一个问题

### ISSUE THREAD

**Issue by 9yues** [liulongbin1314/vue2-preview#1]
![image](https://user-images.githubusercontent.com/19297519/37553241-67e6a012-29ff-11e8-8f6b-074046cb02c9.png)
我用的vue-cli初始化的项目，其他配置都按照你的一步步来了，但是 npm run dev的时候报这个错误，该怎么解决？

**Comment by liulongbin1314** [comment]
问题已经解决，目前可以卸载之前安装的 `vue2-preview`， 并重新运行 `npm i vue2-preview -S` 从而安装使用 `1.0.2`  版本的包解决上述的报错问题；

**Comment by 9yues** [comment]
好的，没事了，我自己封装好了，不过还是谢谢你
