### ISSUE TITLE
斌哥，请问你vue视频里面vscode用的啥主题，一直找不到同款

### ISSUE THREAD

**Issue by huangxu510** [liulongbin1314/vue2-preview#12]
斌哥，请问你vue视频里面vscode用的啥主题，一直找不到同款，也不知道在哪找你问，只能来这里了。。。

**Comment by liulongbin1314** [comment]
我用 Gitee 比 GitHub 多，抱歉刚看到~~~~，用的是这款主题：
https://marketplace.visualstudio.com/items?itemName=liulongbin1314.escook-theme
